### ISSUE TITLE
RealTeam And not Team ?

### ISSUE THREAD

**Issue by warquys** [SynapseSL/Scp106Rework#4]
Wouldn't it be better to check if the player can be attacked by an SCP instead of checking if the player is not an SCP ?

 https://github.com/SynapseSL/Scp106Rework/blob/master/Scp106Rework/EventHandlers.cs#L35
 https://github.com/SynapseSL/Scp106Rework/blob/master/Scp106Rework/EventHandlers.cs#L104

**Comment by GrafDimenzio** [comment]
Yeah it would be better. I assume this uses Real Team since it's a older Plugin and was made before all the current Synapse API systems were introduced

**Comment by warquys** [comment]
ok
